const fs = require('fs');
const file = 'site/lib/hosting/catalog.ts';
let code = fs.readFileSync(file, 'utf8');

code = code.replace(/paymentPlanCode: string;/, 'paymentPlanCode: "basic" | "pro" | "ultra" | "master";');

const newPlans = `export const HOSTING_PLANS: Record<HostingKind, HostingPlan[]> = {
  site: [
    {
      id: "site-start",
      kind: "site",
      name: "Site Start",
      badge: "Iniciante",
      monthlyAmount: 9.99,
      compareMonthlyAmount: 19.99,
      currency: "BRL",
      billingLabel: "/mes",
      cycleBadge: "Para comecar",
      limitedOffer: "O essencial",
      description: "Ideal para sites simples, blogs ou paginas estaticas.",
      specs: ["256 MB RAM", "500 MB SSD NVMe", "1 Site", "SSL Gratuito", "Backup Diario", "Protecao DDoS"],
      paymentPlanCode: "basic",
    },
    {
      id: "site-basic",
      kind: "site",
      name: "Site Basic",
      badge: "Basico",
      monthlyAmount: 14.99,
      compareMonthlyAmount: 29.99,
      currency: "BRL",
      billingLabel: "/mes",
      cycleBadge: "Custo/Beneficio",
      limitedOffer: "Mais recursos",
      description: "Para pequenos projetos e portifolios que precisam de folga.",
      specs: ["384 MB RAM", "750 MB SSD NVMe", "2 Sites", "SSL Gratuito", "Backup Diario", "Protecao DDoS"],
      paymentPlanCode: "basic",
    },
    {
      id: "site-plus",
      kind: "site",
      name: "Site Plus",
      badge: "Plus",
      monthlyAmount: 19.99,
      compareMonthlyAmount: 39.99,
      currency: "BRL",
      billingLabel: "/mes",
      cycleBadge: "Intermediario",
      limitedOffer: "Multiplos sites",
      description: "Para projetos pequenos crescendo e precisando de mais performance.",
      specs: ["512 MB RAM", "1 GB SSD NVMe", "3 Sites", "SSL Gratuito", "Backup Diario", "Protecao DDoS"],
      paymentPlanCode: "pro",
    },
    {
      id: "site-pro",
      kind: "site",
      name: "Site Pro",
      badge: "Popular",
      recommended: true,
      monthlyAmount: 29.99,
      compareMonthlyAmount: 59.99,
      currency: "BRL",
      billingLabel: "/mes",
      cycleBadge: "Para profissionais",
      limitedOffer: "Performance Pro",
      description: "Excelente para SaaS, lojas virtuais e sistemas Web complexos.",
      specs: ["768 MB RAM", "1.5 GB SSD NVMe", "5 Sites", "SSL Gratuito", "Backup Diario", "Protecao DDoS"],
      paymentPlanCode: "pro",
    },
    {
      id: "site-business",
      kind: "site",
      name: "Site Business",
      badge: "Business",
      monthlyAmount: 39.99,
      compareMonthlyAmount: 79.99,
      currency: "BRL",
      billingLabel: "/mes",
      cycleBadge: "Para empresas",
      limitedOffer: "Alta performance",
      description: "Para operacoes e negocios rodando multiplos sites ou aplicacoes.",
      specs: ["1 GB RAM", "2 GB SSD NVMe", "10 Sites", "SSL Gratuito", "Backup Diario", "Protecao DDoS"],
      paymentPlanCode: "ultra",
    },
    {
      id: "site-premium",
      kind: "site",
      name: "Site Premium",
      badge: "Premium",
      monthlyAmount: 49.99,
      compareMonthlyAmount: 99.99,
      currency: "BRL",
      billingLabel: "/mes",
      cycleBadge: "Poder maximo",
      limitedOffer: "Sem limites",
      description: "Hospedagem robusta para sistemas criticos de alta disponibilidade.",
      specs: ["1.5 GB RAM", "3 GB SSD NVMe", "Sites Ilimitados", "SSL Gratuito", "Backup Diario", "Protecao DDoS"],
      paymentPlanCode: "master",
    },
  ],
  bot: [
    {
      id: "bot-nano",
      kind: "bot",
      name: "Bot Nano",
      badge: "Iniciante",
      monthlyAmount: 9.99,
      compareMonthlyAmount: 19.99,
      currency: "BRL",
      billingLabel: "/mes",
      cycleBadge: "Para comecar",
      limitedOffer: "Micro bot",
      description: "O melhor custo-beneficio para bots iniciantes ou em testes.",
      specs: ["128 MB RAM", "250 MB SSD NVMe", "1 Bot", "Reinicio Automatico", "Logs em Tempo Real", "Protecao DDoS"],
      paymentPlanCode: "basic",
    },
    {
      id: "bot-start",
      kind: "bot",
      name: "Bot Start",
      badge: "Start",
      monthlyAmount: 14.99,
      compareMonthlyAmount: 29.99,
      currency: "BRL",
      billingLabel: "/mes",
      cycleBadge: "O basico solido",
      limitedOffer: "Pequenos servers",
      description: "Perfeito para bots com algumas dezenas de servidores ativos.",
      specs: ["256 MB RAM", "500 MB SSD NVMe", "2 Bots", "Reinicio Automatico", "Logs em Tempo Real", "Protecao DDoS"],
      paymentPlanCode: "basic",
    },
    {
      id: "bot-basic",
      kind: "bot",
      name: "Bot Basic",
      badge: "Plus",
      monthlyAmount: 19.99,
      compareMonthlyAmount: 39.99,
      currency: "BRL",
      billingLabel: "/mes",
      cycleBadge: "Crescimento",
      limitedOffer: "Comunidades",
      description: "Para bots moderando comunidades grandes ou fazendo automacoes leves.",
      specs: ["384 MB RAM", "750 MB SSD NVMe", "3 Bots", "Reinicio Automatico", "Logs em Tempo Real", "Protecao DDoS"],
      paymentPlanCode: "pro",
    },
    {
      id: "bot-plus",
      kind: "bot",
      name: "Bot Plus",
      badge: "Popular",
      recommended: true,
      monthlyAmount: 29.99,
      compareMonthlyAmount: 59.99,
      currency: "BRL",
      billingLabel: "/mes",
      cycleBadge: "Escala real",
      limitedOffer: "Para sistemas",
      description: "O plano favorito dos desenvolvedores Discord e WhatsApp. Suporta banco de dados.",
      specs: ["512 MB RAM", "1 GB SSD NVMe", "5 Bots", "Reinicio Automatico", "Logs em Tempo Real", "Protecao DDoS"],
      paymentPlanCode: "pro",
    },
    {
      id: "bot-pro",
      kind: "bot",
      name: "Bot Pro",
      badge: "Pro",
      monthlyAmount: 39.99,
      compareMonthlyAmount: 79.99,
      currency: "BRL",
      billingLabel: "/mes",
      cycleBadge: "Mais poder",
      limitedOffer: "Processo intenso",
      description: "Quando o seu projeto passa da marca de milhares de acessos, esse e o cara.",
      specs: ["768 MB RAM", "1.5 GB SSD NVMe", "10 Bots", "Reinicio Automatico", "Logs em Tempo Real", "Protecao DDoS"],
      paymentPlanCode: "ultra",
    },
    {
      id: "bot-ultra",
      kind: "bot",
      name: "Bot Ultra",
      badge: "Ultra",
      monthlyAmount: 49.99,
      compareMonthlyAmount: 99.99,
      currency: "BRL",
      billingLabel: "/mes",
      cycleBadge: "Hardware maximo",
      limitedOffer: "Operacao Mestra",
      description: "Hospedagem definitiva e profissional para quem precisa criar verdadeiras fazendas de bots.",
      specs: ["1 GB RAM", "2 GB SSD NVMe", "15 Bots", "Reinicio Automatico", "Logs em Tempo Real", "Protecao DDoS"],
      paymentPlanCode: "master",
    },
  ],
};`;

code = code.replace(/export const HOSTING_PLANS: Record<HostingKind, HostingPlan\[\]> = \{[\s\S]*?^};/m, newPlans);

fs.writeFileSync(file, code);
console.log('Done mapping paymentPlanCodes!');
