const CUSTOM_IDS = {
  openTicket: "ticket:open",
  claimTicket: "ticket:claim",
  closeTicket: "ticket:close",
  ticketAdminPanel: "ticket:panel_admin",
  ticketStaffPanel: "ticket:panel_staff",
  ticketMemberPanel: "ticket:panel_member",
  ticketAdminSelect: "ticket:admin_select",
  ticketStaffSelect: "ticket:staff_select",
  ticketMemberSelect: "ticket:member_select",
  ticketAddMemberModal: "ticket:add_member_modal",
  ticketRemoveMemberModal: "ticket:remove_member_modal",
  ticketMemberIdInput: "ticket:member_id",
  ticketPaymentModal: "ticket:payment_modal",
  ticketPaymentAmountInput: "ticket:payment_amount",
  ticketPaymentNoteInput: "ticket:payment_note",
  ticketMemberUpdateModal: "ticket:member_update_modal",
  ticketMemberUpdateInput: "ticket:member_update",
  ticketStaffNoteModal: "ticket:staff_note_modal",
  ticketStaffNoteInput: "ticket:staff_note",
  openTicketReasonModal: "ticket:open_modal",
  openTicketReasonInput: "ticket:open_reason",
  aiSuggestionHelped: "ticket:ai_helped",
  aiSuggestionContinue: "ticket:ai_continue",
};

module.exports = { CUSTOM_IDS };
